export const EndPoints = {
 
 USERS: 'USERS',
 COMPANY: 'Company',
 GROUPUSER: 'GroupUser',
 GROUP: 'Group',
 MESSAGE: 'Message',
 OFFER: 'Offer',
 EVALUATION: 'EvaluationCriteria',
 CHAT:'Chat',
 CHAT_MESSAGE:'ChatMessage',
 PERMISSION:'Permission',
 COMMENT:'Comment',
 NOTIFICATION:'Notification',
 CONSTITUTION:'Constitution',
 CATEGORY:'Category',
 SURVEY:'Survey',
 USER_CATEGORY:'UserCategory',
 FIELD_GROUP:'FieldGroup',
};
